AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties: 
      Handler: "dist/index.handler"
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Sub "codepipeline-${AWS::Region}-${AWS::AccountId}"
        S3Key: lambda.zip
      Runtime: "nodejs16.x"
      Timeout: 30

  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"